### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by princepsycho** [independentcod/RDPWraper#1]
Easy and automatic termsrv.dll patcher for Windows 10 1909 version 18363.959

But it doesnt work ... 

https://i.imgur.com/zk8Rj6G.png

**Comment by ind3p3nd3nt** [comment]
You have to read thought, are the informations in the .ini matching your Windows version, please read carefully and try again
The instructions clearly specifies to disconnect from internet before installing, did you do that?

**Comment by ind3p3nd3nt** [comment]
closing no response from ticket author
